version: '3.6'

services:
  productservice:
    container_name: productservice
    ports:
      - 8020:80
      - 8021:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<your pass>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<your cert name>.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    restart: on-failure
    
  authenticationservice:
    container_name: authenticationservice
    ports:
      - 9000:80
      - 9001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<your pass>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<your cert name>.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    restart: on-failure
    
  priceservice:
    container_name: priceservice
    ports:
      - 8000:80
      - 8001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<your pass>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<your cert name>.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: PriceService/Dockerfile
    restart: on-failure

  imageservice:
    container_name: imageservice
    ports:
      - 8010:80
      - 8011:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<your pass>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/<your cert name>.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: ImageService/Dockerfile
    restart: on-failure    